# Site settings
title: Suresh
header-img: img/home-bg.jpg
email: mail@hsuresh.com
description: "Home"
baseurl: ""
url: "http://hsuresh.com"
twitter_username: itzsuresh
github_username:  hsuresh
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
